/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.phase10;

import java.awt.Point;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yalinzhang
 */
public class Score extends javax.swing.JFrame {
    private Object[][] playersDetails;
    /**
     * Creates new form Score
     */
    public Score(){}
    public Score(GuiManager gManage) {
        initComponents();
        int numPlayers = gManage.mainManager.getGame().getNumberOfPlayers();
        
        Player[] sortedPlayers = new Player[numPlayers];
        for(int i = 0; i<  numPlayers; i++){
            sortedPlayers[i] = gManage.mainManager.getGame().getPlayer(i);
        }
        sortedPlayers = sortPlayers(sortedPlayers);
        playersDetails = new Object[sortedPlayers.length][4];
        for(int i = 0; i< sortedPlayers.length; i++){
            playersDetails[i][0] = i+1;
            playersDetails[i][1] = sortedPlayers[i].getName();
            playersDetails[i][2] = sortedPlayers[i].getPhase();
            playersDetails[i][3] = sortedPlayers[i].getScore();

        table.setModel(new DefaultTableModel(playersDetails, new String[] {"PLACE", "NAME", "CURRENT PHASE", "SCORE"}));

        setResizable(false);

        
        
            
        }
    }
    
    private Player[] sortPlayers(Player[] ps){
        for(int j= ps.length - 1; j> 0; j--){
            int max = ps[0].getScore();
            Player pMax = ps[0];
            int maxIndex = 0;
            for(int i = 1; i<=j ; i++){
                if(ps[i].getScore() > max){
                    max = ps[i].getScore();
                    pMax = ps[i];
                    maxIndex = i;
                }
            }
            ps[maxIndex] = ps[j];
            ps[j] = pMax;
            
        }
        return ps;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        lblTitle = new javax.swing.JLabel();
        lblPlace = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblCurrentPhase = new javax.swing.JLabel();
        lblScore = new javax.swing.JLabel();
        btnOkay = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 720));

        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 720));

        table.setAutoCreateRowSorter(true);
        table.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "PLACE", "NAME", "CURRENT PHASE", "SCORE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setBounds(new java.awt.Rectangle(36, 54, 370, 195));
        table.setFillsViewportHeight(true);
        table.setRowHeight(48);
        table.setShowGrid(true);
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setResizable(false);
            table.getColumnModel().getColumn(1).setResizable(false);
            table.getColumnModel().getColumn(2).setResizable(false);
            table.getColumnModel().getColumn(2).setPreferredWidth(85);
            table.getColumnModel().getColumn(3).setResizable(false);
        }

        lblTitle.setFont(new java.awt.Font(".AppleSystemUIFont", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Score Board");

        lblPlace.setText("jLabel1");
        lblPlace.setBounds(new java.awt.Rectangle(53, 29, 64, 14));

        lblName.setText("jLabel1");
        lblName.setBounds(new java.awt.Rectangle(127, 29, 83, 14));

        lblCurrentPhase.setText("jLabel1");

        lblScore.setText("jLabel1");
        lblScore.setBounds(new java.awt.Rectangle(318, 29, 88, 14));

        btnOkay.setFont(new java.awt.Font(".AppleSystemUIFont", 0, 14)); // NOI18N
        btnOkay.setText("Okay");
        btnOkay.setBounds(new java.awt.Rectangle(174, 300, 89, 23));
        btnOkay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnOkayMouseClicked(evt);
            }
        });
        btnOkay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblPlace)
                                .addGap(66, 66, 66)
                                .addComponent(lblName)
                                .addGap(69, 69, 69)
                                .addComponent(lblCurrentPhase)
                                .addGap(72, 72, 72)
                                .addComponent(lblScore))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(311, 311, 311)
                        .addComponent(btnOkay))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addComponent(lblTitle)))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(lblTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlace)
                    .addComponent(lblName)
                    .addComponent(lblCurrentPhase)
                    .addComponent(lblScore))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOkay)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 605, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkayActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnOkayActionPerformed

    private void btnOkayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOkayMouseClicked
        // TODO add your handling code here:
        setVisible(false);
    }//GEN-LAST:event_btnOkayMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Score.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Score.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Score.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Score.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Score().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOkay;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCurrentPhase;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPlace;
    private javax.swing.JLabel lblScore;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
